### ISSUE TITLE
Workbox module gives errors

### ISSUE THREAD

**Issue by blueneogeo** [nuxt-community/pwa-module#39] opened 2018-03-06 16:35 UTC
I tried two projects, both give me this error multiple times (for different files):

Uncaught (in promise) WorkboxError: The request fpr 'http://localhost:5000/_nuxt/pages/channels/_id.e42804cd97f511c7a4d6.js' failed the criteria to be cached. By default, only responses with 'response.ok = true' are cached.
    at http://localhost:5000/_nuxt/workbox.dev.c21f51f2.js:169:1358
    at Generator.throw (<anonymous>)
    at step (http://localhost:5000/_nuxt/workbox.dev.c21f51f2.js:95:30)
    at http://localhost:5000/_nuxt/workbox.dev.c21f51f2.js:108:13
    at <anonymous>

If I actually access the referenced file, it opens fine in the browser, giving a status 200.

<div align="right"><sub><em>This question is available on <a href="https://nuxtjs.cmty.io">Nuxt.js</a> community (<a href="https://nuxtjs.cmty.io/nuxt-community/pwa-module/issues/c30">#c30</a>)</em></sub></div>

**Comment by amazzoccone** [comment] 2018-03-14 01:57
Hi @blueneogeo check out this issue:
I added to `nuxt.config.js` and works successfully.
```
  workbox: {
      // Workbox options
      dev: true
  },
  modifyUrlPrefix: {
      '/': '/_nuxt/'
  }
```

**Comment by blueneogeo** [comment] 2018-03-14 14:14
Hi amazzoccone, thanks for the tip.

I tried it, but it would not fix the issue for me. I also tried not serving locally but on Zeit. You can see this error in action by going to https://dist-vafaadsptc.now.sh and checking the development console in Chrome. I deploy by doing `nuxt build` and serving the dist directory (or uploading it to Zeit).

The errors remain, but now with the new prefix in the url:

workbox.dev.7002ba07.js:167 Uncaught (in promise) WorkboxError: The request fpr 'https://dist-vafaadsptc.now.sh/_nuxt/layouts/default.a08d248377d70094d8ba.js' failed the criteria to be cached. By default, only responses with 'response.ok = true' are cached.
    at https://dist-vafaadsptc.now.sh/_nuxt/workbox.dev.7002ba07.js:169:1358
    at Generator.throw (<anonymous>)
    at step (https://dist-vafaadsptc.now.sh/_nuxt/workbox.dev.7002ba07.js:95:30)
    at https://dist-vafaadsptc.now.sh/_nuxt/workbox.dev.7002ba07.js:108:13
    at <anonymous>

This is the used nuxt.config.js:

module.exports = {
  // Global environment settings
  env: {
    intercomAppID: 'sf79haa5'
  },

  // Headers of the page
  head: {
    title: 'Nine Connections Dashboard',
    meta: [
      { charset: 'utf-8' },
      { name: 'viewport', content: 'width=device-width, initial-scale=1' },
      { hid: 'description', name: 'description', content: 'Web Client' }
    ],
    link: [
      { rel: 'icon', type: 'image/x-icon', href: '/favicon.ico' }
    ],
    link: [
      { rel: 'stylesheet', href: 'https://fonts.googleapis.com/css?family=Poppins:600,700' }
    ]
  },

  // Customize the progress bar color
  loading: { color: '#3273dc' },

  // Build configuration
  build: {
    postcss: {
      plugins: {
        'postcss-custom-properties': false
      }
    },
    vendor: [
      'vue-class-component',
      'vue-property-decorator'
    ]
  },
  router: {
    mode: 'hash',
    middleware: 'i18n'
  },
  modules: [
    '~/modules/typescript.ts',
    ['@nuxtjs/pwa']
  ],
  plugins: ['~/plugins/buefy', '~/plugins/i18n', '~/plugins/intercom'],
  css: ['~/assets/css/main.sass'],
  mode: 'spa',
  workbox: {
    dev: true
  },
  modifyUrlPrefix: {
      '/': '/_nuxt/'
  },
  manifest: {
    name: 'Nine Connections Dashboard',
    lang: 'en'
  }
}

**Comment by pi0** [comment] 2019-02-07 18:06
Should be fixed with `3.0.0-beta`

**Closed by pi0** 2019-02-07 18:06 UTC

**Comment by vinayakkulkarni** [comment] 2019-03-04 19:36
Seems to be an ongoing issue.

**Comment by pi0** [comment] 2019-03-04 20:14
@vinayakkulkarni We don't have local workbox version anymore! Feel free opening an issue with reproduction code if any problem exists.
