### ISSUE TITLE
Installed PWA breaks due to '/?standalone=true' start_url since version 3.2.1

### ISSUE THREAD

**Issue by FreekVR** [nuxt-community/pwa-module#396] opened 2020-11-13 08:36 UTC
After updating to 3.2.2 I am starting to have issues with a freshly installed PWA which by default runs on ?standalone=true.

I'm getting 404s for several of my bundles in the console, as well as this message:
```
workbox-precaching.prod.js:1 
Workbox is precaching URLs without revision info: /?standalone=true
This is generally NOT safe. Learn more at https://bit.ly/wb-precache****
```

Due to the bundles not being loaded the app is essentially not working. I figure it's trying to load files from a previous build which no longer exist on the server due to hash changes.

It seems if I set my manifest `start_url` to simply `/` this resolves the issue, so the problem seems to be cause by the query param?

**Comment by shadow81627** [comment] 2020-11-14 02:18
Duplicate of #381

**Comment by pi0** [comment] 2020-11-28 14:24
Hi. This issue should be gone with [3.3.0](https://github.com/nuxt-community/pwa-module/releases/tag/v3.3.0).

**Closed by pi0** 2020-11-28 14:24 UTC
